name: example-chrome
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: https://map.highfidelity.com
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Chrome
        uses: cypress-io/github-action@v1
        with:
          browser: chrome

      - uses: actions/upload-artifact@v1
        with:
          name: screenshots-in-chrome
          path: cypress/screenshots

      - uses: actions/upload-artifact@v1
        with:
          name: video-in-chrome
          path: cypress/videos

      - run: npx image-size cypress/screenshots/**/*.png

      # I wonder if GH Actions VM includes any of the tools that
      # can tell us the resolution of a video file
      - run: ffprobe cypress/videos/*.mp4 || true
      - run: mplayer -really-quiet -ao null -vo null -identify -frames 0 cypress/videos/*.mp4 || true
